### ISSUE TITLE
Github:lenve/vhr项目学习总结

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#138]
Github：https://github.com/lenve/vhr
微人事是一个前后端分离的人力资源管理系统，项目采用SpringBoot+Vue开发

作者写的很详细，按照REAMDE介绍的配置走即可，还有视频教程

配置中可参考的附加文档
- [菜鸟教程：Redis 安装](https://www.runoob.com/redis/redis-install.html)
- [简书：Windows 10下安装RabbitMQ服务器及基本配置](https://www.jianshu.com/p/a2c9a4242508)
- [CSDN：redis 安装启动及设置密码<windows>](https://blog.csdn.net/jxshangrao_86/article/details/76568416)
- [掘金：nodejs、npm 环境配置步骤(windows版本)](https://juejin.im/post/6844903586313273358)

**Comment by peteryuanpan** [comment]
步骤1-6，完成

根据文档，我需要执行下面步骤
```
1.clone 项目到本地 git@github.com:lenve/vhr.git
2.数据库脚本使用 Flyway 管理，不需要手动导入数据库脚本，只需要提前在本地 MySQL 中创建一个空的数据库 vhr，并修改项目中关于数据的配置（resources 目录下的 application.properties 文件中）即可
3.提前准备好 Redis，在 项目的 application.properties 文件中，将 Redis 配置改为自己的
4.提前准备好 RabbitMQ，在项目的 application.properties 文件中将 RabbitMQ 的配置改为自己的（注意，RabbitMQ 需要分别修改 mailserver 和 vhrserver 的配置文件）
5.在 IntelliJ IDEA 中打开 vhr 项目，启动 mailserver 模块
6.运行 vhrserver 中的 vhr-web 模块
```

上面的步骤，需要安装Mysql、Redis、RabbitMQ，根据附加文档一步步走下来即可，这一块属于后端的部署，我执行还算比较顺利，就不一一记录了

安装完后，按下面步骤运行
- 运行 cmd，执行命令 rabbitmq-server.bat，启动MQ
- 到目录 D:\download\Redis-x64-5.0.9 下，运行 cmd，执行命令 redis-server.exe redis.windows.conf，启动 redis
- IDEA中运行 SpringBootApplication 的 run 方法
- 浏览器访问 http://localhost:8081/index.html

测试效果，ok
![image](https://user-images.githubusercontent.com/10209135/98430897-f719d200-20eb-11eb-93b0-2f89489908a3.png)

备份一下application.yml
```yml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: #nopasswrd
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
```
