### ISSUE TITLE
如何优雅的访问oversea-website

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#5]
### 使用v2ray服务端 + V2RayN客户端

操作步骤
#### 服务端
- 购买一台云主机（**物理位置：香港**），阿里云、腾讯云、七牛云皆可（需要先注册账号、实名认证）
- 本地执行命令：ssh root@serverip，输入密码，登陆云主机
- 云主机上执行命令：bash <(curl -s -L https://git.io/v2ray.sh)
- 然后会有配置流程指南，逐一配置好信息，比如port、password、cipher等
- 配置完成后，再执行命令 v2ray 也会有操作指南，输入1可以查看配置，输入2可以修改配置
![image](https://user-images.githubusercontent.com/10209135/94354881-056adc00-00b2-11eb-8189-049b9808a741.png)
- 建议配置如下
```
 地址 (Address) = <serverip，不需要配置>
 端口 (Port) = 12345
 用户ID (User ID / UUID) = <uuid，会自动生成>
 额外ID (Alter Id) = 0
 传输协议 (Network) = tcp
 伪装类型 (header type) = http
```
- 到云主机的portal管理界面上，找到安全组，允许协议+端口访问（比如上面是tcp协议+端口12345，则安全组上配置之），这一步很重要，否则会无法连接

#### 客户端
- windows10系统，从 https://github.com/2dust/v2rayN/releases 下载最新客户端，注意，要下载v2rayN-Core.zip的，不要下载v2rayN.zip
- 解压zip文件，会得到v2rayN.exe
- 在服务端输入v2ray url，可以得到如下界面
![image](https://user-images.githubusercontent.com/10209135/94354899-19164280-00b2-11eb-818f-cff805c757c3.png)
- 将url复制到剪贴板
- 打开v2rayN.exe，点击服务器 - 从剪贴板导入批量URL，会自动导入服务端配置
![image](https://user-images.githubusercontent.com/10209135/94354931-4f53c200-00b2-11eb-9ce9-8324e15fb0be.png)
- 回到v2rayN.exe，点击参数设置，按图配置好参数
![image](https://user-images.githubusercontent.com/10209135/94354970-93df5d80-00b2-11eb-8c4c-005042031d55.png)
- 点击core:路由设置，按图配置好参数，点击确定
![image](https://user-images.githubusercontent.com/10209135/94354978-9e99f280-00b2-11eb-90c0-8a565d7110f6.png)
- 若下面的控制台打印出【配置成功】、【V2Ray 4.27.0 started】等，则表示ok
![image](https://user-images.githubusercontent.com/10209135/94354994-bec9b180-00b2-11eb-864e-ef953294da0d.png)
- 访问 https://youtube.com 进行测试
- 更多配置细节，参考：https://hijk.art/v2rayn-config-tutorial/

**Comment by peteryuanpan** [comment]
补充 windows上系统代理自动关闭或打开 解决办法
https://github.com/Fndroid/clash_for_windows_pkg/issues/312

**Comment by peteryuanpan** [comment]
### 使用v2ray服务端 + clash客户端

此方法在macos上可成功，在win10上会遇到问题，我没有解决

操作步骤
- 准备一台云主机（物理位置：香港），阿里云、腾讯云、七牛云皆可
- 云主机上执行命令：bash <(curl -s -L https://git.io/v2ray.sh)
然后会有配置流程指南，逐一配置好信息，比如port、password、cipher等
再执行命令 v2ray 也会有操作指南
- macos系统，从 https://github.com/yichengchen/clashX/releases 下载最新客户端
- windows系统，从 https://github.com/Fndroid/clash_for_windows_pkg/releases 下载最新客户端
- 打开clashX，找到「配置」-「打开本地配置文件夹」，会弹出本地文件夹
- 修改本地文件夹下的config.yaml文件
（其中serverip、port、uuid等配置，需要与服务端配置的一样）
- 配置文本参考：https://www.v2rayssr.com/clashxx.html
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''

Proxy:
  - name: pan  # 软件显示的节点名字
    type: vmess # 代理类型
    server: <serverip> # 服务器IP
    port: <port> # 端口号
    uuid: <uuid> # uuid，服务端可查询
    alterId: 64  #额外的ID
    cipher: auto # 加密类型
```
- 到云主机的portal管理界面上，找到安全组，允许 tcp - port 访问（比如允许tcp端口12345）
- 在clashX中，点击「设置为系统代理」（此时已经可以访问 https://www.youtube.com/ 了，在baidu搜索中输入ip会发现检测结果为<serverip>）
- 补充 windows上系统代理自动关闭或打开 解决办法
https://github.com/Fndroid/clash_for_windows_pkg/issues/312
